/**
 * Golden parity tests for the expression evaluator (#30).
 *
 * Every expected value was generated by executing the standalone editor's
 * patched `evalExpression` core (`new Function` semantics, reference file
 * lines 2250–2255) in Node — these tests are the port's parity contract.
 */
import { describe, expect, it } from 'vitest'
import { evaluateExpression } from './expression-evaluator'

describe('evaluateExpression', () => {
  describe('arithmetic, precedence and associativity', () => {
    it.each<[string, number]>([
      ['2+3*4', 14],
      ['10-4/2', 8],
      ['(2+3)*4', 20],
      ['7/2', 3.5],
      ['8/4/2', 1], // '/' is left-associative
      ['10-3-2', 5], // '-' is left-associative
      ['2**3**2', 512], // '**' is right-associative
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })
  })

  describe('unary signs', () => {
    it.each<[string, number]>([
      ['-5+3', -2],
      ['2*-3', -6],
      ['-(2+3)', -5],
      ['+5', 5],
      ['2**-1', 0.5],
      ['- -4', 4],
      ['(-2)**2', 4],
      ['2**2**-1', 2 ** 0.5],
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })

    // JS rejects a unary sign as the left operand of '**' with a
    // SyntaxError; the original caught that and returned NaN.
    it.each([['-2**2'], ['2*-3**2'], ['2**-3**2'], ['- -2**2']])('%s → NaN', (input) => {
      expect(Number.isNaN(evaluateExpression(input))).toBe(true)
    })
  })

  describe('number literals', () => {
    it.each<[string, number]>([
      ['.5+.5', 1],
      ['5.', 5],
      ['1e3', 1000],
      ['1.5e-2', 0.015],
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })

    it.each([['2e'], ['1.5.2']])('malformed literal %s → NaN', (input) => {
      expect(Number.isNaN(evaluateExpression(input))).toBe(true)
    })
  })

  describe('functions', () => {
    it.each<[string, number]>([
      ['sqrt(9)', 3],
      ['abs(-4.5)', 4.5],
      ['pow(2,10)', 1024],
      ['min(3,1,2)', 1],
      ['max(3,1,2)', 3],
      ['min()', Infinity], // Math.min() with no args, as in the original
      ['round(2.5)', 3],
      ['round(-2.5)', -2], // Math.round semantics, not half-away-from-zero
      ['floor(1.9)', 1],
      ['ceil(1.1)', 2],
      ['log(1000)', 3], // log = log10
      ['ln(e)', 1], // ln = natural log
      ['sin(0)', 0],
      ['cos(0)', 1],
      ['tan(0)', 0],
      ['sin(pi/2)', 1],
      ['sqrt(pow(3,2)+pow(4,2))', 5],
      ['max(min(5,10),2**2)', 5],
      ['sqrt(4,9)', 2], // extra args ignored, like Math.sqrt(4, 9)
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })

    it('pow(2) → NaN (missing argument, like Math.pow(2))', () => {
      expect(Number.isNaN(evaluateExpression('pow(2)'))).toBe(true)
    })
  })

  describe('constants', () => {
    it.each<[string, number]>([
      ['pi', Math.PI],
      ['e', Math.E],
      ['2*pi', 2 * Math.PI],
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })
  })

  describe('non-finite results pass through raw (only errors become NaN)', () => {
    it.each<[string, number]>([
      ['1/0', Infinity],
      ['-1/0', -Infinity],
      ['log(0)', -Infinity],
    ])('%s → %d', (input, expected) => {
      expect(evaluateExpression(input)).toBe(expected)
    })

    it.each([['0/0'], ['sqrt(-1)']])('%s → NaN', (input) => {
      expect(Number.isNaN(evaluateExpression(input))).toBe(true)
    })
  })

  describe('malformed and hostile input → NaN, never throws', () => {
    const cases: string[] = [
      '',
      '   ',
      '2+',
      '(2+3',
      '2+*3',
      '2**',
      'foo',
      'foo(2)',
      '2px',
      'pi(2)', // constant is not callable
      'sqrt', // bare function name is not a value
      'sqrt+1',
      '"str"',
      '2;3',
      '2 3',
      'a.b',
      'alert(1)',
      'process.exit()',
      'constructor',
      '__proto__',
      'while(true){}',
      '(()=>{})()',
      '[1,2]',
      '2(3)',
      '2,3', // JS comma operator — documented deviation: NaN here
      '(1,2)', // JS comma operator — documented deviation: NaN here
      '0x10', // hex literal — documented deviation: NaN here
      '10%3', // '%' operator — documented deviation: NaN here
      'min(,2)',
      '1)(',
    ]

    it.each(cases.map((c) => [c]))('%j → NaN without throwing', (input) => {
      let value = 0
      expect(() => {
        value = evaluateExpression(input)
      }).not.toThrow()
      expect(Number.isNaN(value)).toBe(true)
    })
  })
})
