/**
 * Pure expression evaluator for the LaTeX editor (PRD #28, slice 2 — #30).
 *
 * Replaces the `new Function(...)` core of the standalone editor's patched
 * `evalExpression` (reference file
 * latexEditor/latex_editor_FIXED_JSON_IMPORT_COMPLETE_OUTPUT_AS_INPUT_LATEX_FIX.htm.html,
 * "FINAL PATCH" layer, lines 2250–2255) with a tokenizer + recursive-descent
 * parser, because the production CSP has no `unsafe-eval`. No `eval` or
 * `new Function` anywhere in this module.
 *
 * Scope: the math grammar only. LaTeX normalisation (latex-normalise, this
 * slice) and variable-name substitution (field-resolver, slice 5) run BEFORE
 * this, exactly as in the original pipeline.
 *
 * Parity contract (golden tests generated by executing the original in Node):
 * - Grammar: numbers (incl. `.5`, `5.`, `1e3`), `+ - * / **`, unary +/-,
 *   parentheses, function calls with comma-separated arguments.
 * - Functions: sqrt abs pow sin cos tan log(=log10) ln(=natural log) min max
 *   round floor ceil — applied as the corresponding `Math.*` with whatever
 *   argument count was parsed, so `pow(2)` → NaN and `min()` → Infinity,
 *   matching the original's JS semantics.
 * - Constants: `pi`, `e`.
 * - Any parse or evaluation error yields NaN — this function never throws.
 * - Non-finite RESULTS pass through raw (`1/0` → Infinity, `0/0` → NaN);
 *   only errors are mapped to NaN.
 * - `-2**2` → NaN: JS rejects unary minus as the left operand of `**` with a
 *   SyntaxError, which the original caught and turned into NaN. The parser
 *   reproduces that (while `2**-1` → 0.5 and `(-2)**2` → 4 stay valid).
 *
 * Documented deviations (degenerate inputs, agreed in #30 planning): the JS
 * comma operator (`(1,2)` → 2 in the original), hex/octal literals (`0x10`)
 * and the `%` operator were accepted by `new Function`; here they are parse
 * errors → NaN.
 *
 * Pure and DOM-free — reusable by the future student-facing renderer.
 */

type Token =
  | { readonly kind: 'number'; readonly value: number }
  | { readonly kind: 'ident'; readonly name: string }
  | { readonly kind: 'op'; readonly op: '+' | '-' | '*' | '/' | '**' }
  | { readonly kind: 'lparen' }
  | { readonly kind: 'rparen' }
  | { readonly kind: 'comma' }

class ParseError extends Error {}

/**
 * Injected functions, mirroring the original's `new Function` parameter list:
 * `log` is base-10, `ln` is the natural logarithm. Maps (not plain objects)
 * so hostile identifiers like `constructor` can never hit the prototype chain.
 */
const FUNCTIONS = new Map<string, (...args: number[]) => number>([
  ['sqrt', Math.sqrt],
  ['abs', Math.abs],
  ['pow', Math.pow],
  ['sin', Math.sin],
  ['cos', Math.cos],
  ['tan', Math.tan],
  ['log', Math.log10],
  ['ln', Math.log],
  ['min', Math.min],
  ['max', Math.max],
  ['round', Math.round],
  ['floor', Math.floor],
  ['ceil', Math.ceil],
])

const CONSTANTS = new Map<string, number>([
  ['pi', Math.PI],
  ['e', Math.E],
])

const NUMBER_RE = /(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/y
const IDENT_RE = /[A-Za-z_]\w*/y

function tokenize(input: string): Token[] {
  const tokens: Token[] = []
  let i = 0
  while (i < input.length) {
    const ch = input[i]
    if (/\s/.test(ch)) {
      i++
      continue
    }
    NUMBER_RE.lastIndex = i
    const num = NUMBER_RE.exec(input)
    if (num) {
      tokens.push({ kind: 'number', value: Number(num[0]) })
      i = NUMBER_RE.lastIndex
      continue
    }
    IDENT_RE.lastIndex = i
    const ident = IDENT_RE.exec(input)
    if (ident) {
      tokens.push({ kind: 'ident', name: ident[0] })
      i = IDENT_RE.lastIndex
      continue
    }
    if (input.startsWith('**', i)) {
      tokens.push({ kind: 'op', op: '**' })
      i += 2
      continue
    }
    if (ch === '+' || ch === '-' || ch === '*' || ch === '/') {
      tokens.push({ kind: 'op', op: ch })
      i++
      continue
    }
    if (ch === '(') {
      tokens.push({ kind: 'lparen' })
      i++
      continue
    }
    if (ch === ')') {
      tokens.push({ kind: 'rparen' })
      i++
      continue
    }
    if (ch === ',') {
      tokens.push({ kind: 'comma' })
      i++
      continue
    }
    throw new ParseError(`unexpected character "${ch}"`)
  }
  return tokens
}

/**
 * Evaluates an already-normalised, already-substituted math expression.
 * Returns the numeric result (including ±Infinity), or NaN on any parse or
 * evaluation error. Never throws.
 */
export function evaluateExpression(expr: string): number {
  if (!expr || !expr.trim()) return NaN
  try {
    const tokens = tokenize(expr)
    let pos = 0

    function isOp(op: '+' | '-' | '*' | '/' | '**'): boolean {
      const t = tokens[pos]
      return t !== undefined && t.kind === 'op' && t.op === op
    }

    function expect(kind: 'rparen', message: string): void {
      const t = tokens[pos]
      if (!t || t.kind !== kind) throw new ParseError(message)
      pos++
    }

    // additive := multiplicative (('+' | '-') multiplicative)*
    function parseAdditive(): number {
      let left = parseMultiplicative()
      while (isOp('+') || isOp('-')) {
        const minus = isOp('-')
        pos++
        const right = parseMultiplicative()
        left = minus ? left - right : left + right
      }
      return left
    }

    // multiplicative := unary (('*' | '/') unary)*
    function parseMultiplicative(): number {
      let left = parseUnary()
      while (isOp('*') || isOp('/')) {
        const div = isOp('/')
        pos++
        const right = parseUnary()
        left = div ? left / right : left * right
      }
      return left
    }

    // unary := ('+' | '-') signedOperand | exponent
    // A sign-prefixed expression must not be followed by '**' — JS makes
    // `-2**2` a SyntaxError, which the original surfaced as NaN.
    function parseUnary(): number {
      if (isOp('+') || isOp('-')) {
        const value = parseSignedOperand()
        if (isOp('**')) throw new ParseError('unary operand cannot precede **')
        return value
      }
      return parseExponent()
    }

    // signedOperand := ('+' | '-') signedOperand | primary
    // Deliberately parses only a primary after the sign(s): the '**' that a
    // full exponent parse would swallow must stay visible to parseUnary.
    function parseSignedOperand(): number {
      if (isOp('+') || isOp('-')) {
        const minus = isOp('-')
        pos++
        const operand = parseSignedOperand()
        return minus ? -operand : operand
      }
      return parsePrimary()
    }

    // exponent := primary ('**' unary)?   — right-associative: 2**3**2 = 512
    function parseExponent(): number {
      const base = parsePrimary()
      if (isOp('**')) {
        pos++
        const exponent = parseUnary()
        return base ** exponent
      }
      return base
    }

    // primary := NUMBER | CONST | FN '(' [additive (',' additive)*] ')' | '(' additive ')'
    function parsePrimary(): number {
      const t = tokens[pos]
      if (!t) throw new ParseError('unexpected end of input')
      if (t.kind === 'number') {
        pos++
        return t.value
      }
      if (t.kind === 'ident') {
        pos++
        const next = tokens[pos]
        if (next && next.kind === 'lparen') {
          pos++
          const fn = FUNCTIONS.get(t.name)
          if (!fn) throw new ParseError(`unknown function "${t.name}"`)
          const args: number[] = []
          if (!tokens[pos] || tokens[pos].kind !== 'rparen') {
            args.push(parseAdditive())
            while (tokens[pos] && tokens[pos].kind === 'comma') {
              pos++
              args.push(parseAdditive())
            }
          }
          expect('rparen', 'expected ")" after function arguments')
          return fn(...args)
        }
        const constant = CONSTANTS.get(t.name)
        if (constant === undefined) throw new ParseError(`unknown identifier "${t.name}"`)
        return constant
      }
      if (t.kind === 'lparen') {
        pos++
        const value = parseAdditive()
        expect('rparen', 'expected ")"')
        return value
      }
      throw new ParseError('unexpected token')
    }

    const result = parseAdditive()
    if (pos !== tokens.length) throw new ParseError('unexpected trailing input')
    return result
  } catch {
    return NaN
  }
}
