/**
 * Golden parity tests for field-resolver (#33, resolveFieldPlaceholders #34).
 *
 * Every expected value was generated by executing the standalone editor's
 * consolidated field-system composition (base `getFieldValue`/
 * `getAutoExpression` + FINAL PATCH wrapper/`evalExpression` + the final
 * `resolveFieldPlaceholders` of `patch-output-as-input-latex-fix-v1` +
 * display-formatting `formatValue` — see the module header for reference
 * lines) in Node with plain-object field stubs. These tests are the port's
 * parity contract, quirks included — notably that name/token CYCLES collapse
 * to `(0)` → 0 instead of „Err" (visited sets guarantee termination; „Err"
 * is reserved for non-finite results such as empty or invalid expressions),
 * and that `[output:x]` write-backs persist the raw `String(v)` — floating
 * point noise included.
 */
import { describe, expect, it } from 'vitest'
import {
  autoExpressionForOutput,
  classifyTypedPlaceholder,
  evalFieldExpression,
  fieldDisplay,
  findDuplicateName,
  getFieldByName,
  getFieldValue,
  resolveFieldPlaceholders,
  type FieldData,
  type FieldGraph,
  type LineToken,
} from './field-resolver'

// --- test harness -----------------------------------------------------------

function input(id: string, name: string, value: string): FieldData {
  return { id, type: 'input', name, refType: 'static', value }
}

function refInput(id: string, name: string, refId: string): FieldData {
  return { id, type: 'input', name, refType: 'ref', refId }
}

function output(id: string, name: string, expr: string, latexValue?: string): FieldData {
  const f: FieldData = { id, type: 'output', name, expr }
  if (latexValue !== undefined) f.latexValue = latexValue
  return f
}

/**
 * Builds line tokens from a template string: every character becomes a char
 * token, `§1`…`§9` become field tokens for `marks[n]` (the way the DOM
 * adapter tokenizes a line with embedded pills).
 */
function toks(template: string, marks: Record<string, string> = {}): LineToken[] {
  const tokens: LineToken[] = []
  let i = 0
  while (i < template.length) {
    const m = /^§(\d)/.exec(template.slice(i))
    if (m) {
      tokens.push({ fieldId: marks[m[1]] })
      i += 2
    } else {
      tokens.push({ char: template[i] })
      i++
    }
  }
  return tokens
}

function graphOf(fields: FieldData[], lines: Record<string, LineToken[]> = {}): FieldGraph {
  return {
    byId: (id) => fields.find((f) => f.id === id) ?? null,
    all: () => fields,
    lineTokensFor: (fieldId) => lines[fieldId] ?? null,
  }
}

/**
 * Graph whose `setLatexValue` mutates the FieldData objects exactly the way
 * the DOM adapter mutates `dataset.latexValue` (`String(v)` / delete) — the
 * write-back must be visible to later placeholders within the same
 * resolution pass — and records every call for assertions.
 */
function mutableGraphOf(
  fields: FieldData[],
  lines: Record<string, LineToken[]> = {}
): { graph: FieldGraph; writes: { id: string; v: number }[] } {
  const writes: { id: string; v: number }[] = []
  return {
    graph: {
      ...graphOf(fields, lines),
      setLatexValue: (id, v) => {
        writes.push({ id, v })
        const f = fields.find((x) => x.id === id)
        if (!f) return
        if (Number.isFinite(v)) f.latexValue = String(v)
        else delete f.latexValue
      },
    },
    writes,
  }
}

// --- getFieldValue: static values ---------------------------------------------

describe('getFieldValue — static inputs (parseFloat semantics)', () => {
  it.each<[string, number]>([
    ['2', 2],
    ['2.5', 2.5],
    ['2abc', 2], // parseFloat quirk preserved
    ['', NaN],
    ['abc', NaN],
  ])('value %j → %p', (value, expected) => {
    const g = graphOf([input('a', 'a', value)])
    expect(getFieldValue(g, 'a')).toBe(expected)
  })

  it('unknown field id → NaN', () => {
    expect(getFieldValue(graphOf([]), 'nope')).toBeNaN()
  })
})

// --- getFieldValue: references -------------------------------------------------

describe('getFieldValue — references', () => {
  it('input referencing an output with a manual expression', () => {
    const g = graphOf([refInput('rin', '', 'out1'), output('out1', 'res', '2+3')])
    expect(getFieldValue(g, 'rin')).toBe(5)
  })

  it('chain: ref input → output whose expression names another input', () => {
    const g = graphOf([
      refInput('chain', '', 'out2'),
      output('out2', 'twice', 'basis*2'),
      input('basis', 'basis', '4'),
    ])
    expect(getFieldValue(g, 'chain')).toBe(8)
  })
})

// --- getFieldValue: cycles terminate -------------------------------------------

describe('getFieldValue — cycles terminate (reference collapses them to 0, not Err)', () => {
  it('input↔output mutual cycle: both resolve to 0', () => {
    const fields = [refInput('inA', 'inA', 'outB'), output('outB', 'outB', 'inA')]
    expect(getFieldValue(graphOf(fields), 'outB')).toBe(0)
    expect(getFieldValue(graphOf(fields), 'inA')).toBe(0)
  })

  it('output↔output name cycle: both resolve to 0', () => {
    const fields = [output('o1', 'o1', 'o2'), output('o2', 'o2', 'o1')]
    expect(getFieldValue(graphOf(fields), 'o1')).toBe(0)
    expect(getFieldValue(graphOf(fields), 'o2')).toBe(0)
  })

  it('output whose expression names itself resolves to 0', () => {
    const g = graphOf([output('selfo', 'selfa', 'selfa')])
    expect(getFieldValue(g, 'selfo')).toBe(0)
  })
})

// --- getFieldValue: stored latexValue short-circuit -----------------------------

describe('getFieldValue — stored latexValue (output-as-input rule boundary)', () => {
  it('empty-expr output returns its stored LaTeX value', () => {
    const g = graphOf([output('lv', 'lv', '', '42')])
    expect(getFieldValue(g, 'lv')).toBe(42)
  })

  it('short-circuit beats the visited check (no Err even mid-cycle)', () => {
    const g = graphOf([output('lv', 'lv', '', '42')])
    expect(getFieldValue(g, 'lv', new Set(['lv']))).toBe(42)
  })

  it('a manual expression wins over the stored value', () => {
    const g = graphOf([output('lv2', 'lv2', '1+1', '42')])
    expect(getFieldValue(g, 'lv2')).toBe(2)
  })

  it('non-numeric stored value falls through to normal resolution', () => {
    const g = graphOf([output('lv3', 'lv3', '', 'abc')])
    expect(getFieldValue(g, 'lv3')).toBeNaN()
  })
})

// --- auto-expression boundaries --------------------------------------------------

describe('autoExpressionForOutput — boundary golden cases', () => {
  const out = output('out', 'out', '')

  it('between ":" and "=": „Berechnung: 2+4*3 = [out]"', () => {
    const g = graphOf([out], { out: toks('Berechnung: 2+4*3 = §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('2+4*3')
    expect(getFieldValue(g, 'out')).toBe(14)
  })

  it('between two "=": „a = 2+2 = [out]"', () => {
    const g = graphOf([out], { out: toks('a = 2+2 = §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('2+2')
    expect(getFieldValue(g, 'out')).toBe(4)
  })

  it('line start to "=": „2*3 = [out]"', () => {
    const g = graphOf([out], { out: toks('2*3 = §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('2*3')
    expect(getFieldValue(g, 'out')).toBe(6)
  })

  it('no "=" on the line → empty expression → Err display', () => {
    const g = graphOf([out], { out: toks('kein Gleichheitszeichen §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('')
    expect(getFieldValue(g, 'out')).toBeNaN()
    expect(fieldDisplay(g, 'out')).toEqual({ text: 'Err', isError: true, isRef: false })
  })

  it('an "=" only AFTER the output does not count: „[out] = 3"', () => {
    const g = graphOf([out], { out: toks('§1 = 3', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('')
  })

  it('":" occurring after an earlier "=" is the start boundary: „a = b: 5 = [out]"', () => {
    const g = graphOf([out], { out: toks('a = b: 5 = §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('5')
    expect(getFieldValue(g, 'out')).toBe(5)
  })

  it('pill tokens are substituted by their values: „Preis: [5] * 2 = [out]"', () => {
    const g = graphOf([input('preis', 'Preis', '5'), out], {
      out: toks('Preis: §1 * 2 = §2', { 1: 'preis', 2: 'out' }),
    })
    expect(autoExpressionForOutput(g, 'out')).toBe('(5) * 2')
    expect(getFieldValue(g, 'out')).toBe(10)
  })

  it('non-finite pill tokens become (0): „x: [abc] + 1 = [out]"', () => {
    const g = graphOf([input('bad', 'bad', 'abc'), out], {
      out: toks('x: §1 + 1 = §2', { 1: 'bad', 2: 'out' }),
    })
    expect(autoExpressionForOutput(g, 'out')).toBe('(0) + 1')
    expect(getFieldValue(g, 'out')).toBe(1)
  })

  it('two outputs on one line each use their own preceding "="', () => {
    const out1 = output('out1', 'o1', '')
    const out2 = output('out2', 'o2', '')
    const line = toks('a: 1+1 = §1, b: 2+2 = §2', { 1: 'out1', 2: 'out2' })
    const g = graphOf([out1, out2], { out1: line, out2: line })
    expect(autoExpressionForOutput(g, 'out1')).toBe('1+1')
    expect(autoExpressionForOutput(g, 'out2')).toBe('2+2')
    expect(getFieldValue(g, 'out1')).toBe(2)
    expect(getFieldValue(g, 'out2')).toBe(4)
  })

  it('quirk: the FIRST token with the output id wins — a clone earlier in the line hides the "="', () => {
    // "[out] 2+2 = [out]": findIndex hits the first pill, no "=" before it.
    const g = graphOf([out], { out: toks('§1 2+2 = §1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('')
  })

  it('quirk: with the pill doubled AFTER the "=", the first occurrence still resolves: „5 = [out][out]"', () => {
    const g = graphOf([out], { out: toks('5 = §1§1', { 1: 'out' }) })
    expect(autoExpressionForOutput(g, 'out')).toBe('5')
  })

  it('no line context (hidden store / unknown) → empty expression', () => {
    const g = graphOf([out])
    expect(autoExpressionForOutput(g, 'out')).toBe('')
  })
})

// --- evalFieldExpression ----------------------------------------------------------

describe('evalFieldExpression — name substitution and LaTeX pipeline', () => {
  it('substitutes a variable name: "preis * 2" with preis=100 → 200', () => {
    const g = graphOf([input('p1', 'preis', '100')])
    expect(evalFieldExpression(g, 'preis * 2')).toBe(200)
  })

  it('longest name first: "preisNetto + preis" → 150', () => {
    const g = graphOf([input('p1', 'preis', '100'), input('p2', 'preisNetto', '50')])
    expect(evalFieldExpression(g, 'preisNetto + preis')).toBe(150)
  })

  it('names that are no valid identifiers are never substituted: "2x" → NaN', () => {
    const g = graphOf([input('n1', '2x', '5')])
    expect(evalFieldExpression(g, '2x')).toBeNaN()
  })

  it('negative values are parenthesised: "x * 2" with x=-5 → -10', () => {
    const g = graphOf([input('x1', 'x', '-5')])
    expect(evalFieldExpression(g, 'x * 2')).toBe(-10)
  })

  it('output names resolve through their expressions: "summe * 10" → 40', () => {
    const g = graphOf([input('a1', 'a', '2'), output('sum', 'summe', 'a + a')])
    expect(evalFieldExpression(g, 'summe * 10')).toBe(40)
  })

  it.each<[string, number]>([
    ['1,5 + 1', 2.5], // German decimal comma via normalisation
    ['2^3', 8], // ^ → **
  ])('%j → %p (LaTeX normalisation runs first)', (expr, expected) => {
    expect(evalFieldExpression(graphOf([]), expr)).toBe(expected)
  })

  it('normalisation happens BEFORE substitution: "\\frac{preis}{4}" → 25', () => {
    const g = graphOf([input('p1', 'preis', '100')])
    expect(evalFieldExpression(g, '\\frac{preis}{4}')).toBe(25)
  })

  it.each<[string]>([[''], ['   '], ['y + 1']])('%j → NaN', (expr) => {
    expect(evalFieldExpression(graphOf([]), expr)).toBeNaN()
  })
})

// --- getFieldByName ------------------------------------------------------------------

describe('getFieldByName', () => {
  const fields = [input('a1', 'preis', '1'), input('a2', 'preis', '2'), input('a3', 'menge', '3')]

  it('returns the first match in document order', () => {
    expect(getFieldByName(graphOf(fields), 'preis')?.id).toBe('a1')
  })

  it('is exact (case-sensitive), empty names never match', () => {
    expect(getFieldByName(graphOf(fields), 'Preis')).toBeNull()
    expect(getFieldByName(graphOf(fields), '')).toBeNull()
  })
})

// --- findDuplicateName ----------------------------------------------------------------

describe('findDuplicateName — unique-name enforcement', () => {
  it('finds a duplicate case-insensitively and trimmed', () => {
    const g = graphOf([input('a1', 'Preis', '1'), input('a2', 'menge', '2')])
    expect(findDuplicateName(g, 'preis', 'a2')?.id).toBe('a1')
    expect(findDuplicateName(g, '  PREIS  ', 'a2')?.id).toBe('a1')
  })

  it('the edited field itself and its clones never count', () => {
    const g = graphOf([input('a1', 'Preis', '1'), input('a1', 'Preis', '1')])
    expect(findDuplicateName(g, 'preis', 'a1')).toBeNull()
  })

  it('empty and whitespace-only names are never duplicates', () => {
    const g = graphOf([input('a1', '', '1'), input('a2', ' ', '2')])
    expect(findDuplicateName(g, '', 'a3')).toBeNull()
    expect(findDuplicateName(g, '   ', 'a3')).toBeNull()
  })
})

// --- classifyTypedPlaceholder ------------------------------------------------------------

describe('classifyTypedPlaceholder — typed [input:x]/[output:x] conversion rule', () => {
  const inField = input('i', 'x', '1')
  const outField = output('o', 'y', '')

  it.each<['input' | 'output', FieldData | null, string]>([
    ['input', inField, 'visible-input-clone'],
    ['output', outField, 'output-reference'],
    ['input', outField, 'keep-text'], // kind mismatch stays literal text
    ['output', inField, 'keep-text'],
    ['input', null, 'keep-text'], // unknown name stays literal text
  ])('kind %j on %o → %j', (kind, field, expected) => {
    expect(classifyTypedPlaceholder(kind, field)).toBe(expected)
  })
})

// --- fieldDisplay ---------------------------------------------------------------------------

describe('fieldDisplay — pill display state', () => {
  it('static inputs show the RAW value string (no German formatting)', () => {
    expect(fieldDisplay(graphOf([input('i1', 'i1', '1000')]), 'i1')).toEqual({
      text: '1000',
      isError: false,
      isRef: false,
    })
  })

  it('empty static value falls back to "0"', () => {
    expect(fieldDisplay(graphOf([input('i2', 'i2', '')]), 'i2')).toEqual({
      text: '0',
      isError: false,
      isRef: false,
    })
  })

  it('reference inputs show the German-formatted referenced value', () => {
    const g = graphOf([refInput('r1', '', 'o1'), output('o1', 'o1', '2500.5')])
    expect(fieldDisplay(g, 'r1')).toEqual({ text: '2 501', isError: false, isRef: true })
  })

  it('broken references show "—" (formatValue of NaN), not Err', () => {
    const g = graphOf([refInput('r2', '', 'missing')])
    expect(fieldDisplay(g, 'r2')).toEqual({ text: '—', isError: false, isRef: true })
  })

  it.each<[string, string]>([
    ['2+2', '4'],
    ['1/2', '0,5'],
    ['10/3', '3,333'],
    ['1234567.891', '1 234 568'],
  ])('outputs are German-formatted: %j → %j', (expr, text) => {
    const g = graphOf([output('o', 'o', expr)])
    expect(fieldDisplay(g, 'o')).toEqual({ text, isError: false, isRef: false })
  })

  it('non-finite outputs show Err with the error flag', () => {
    const g = graphOf([output('o3', 'o3', '')])
    expect(fieldDisplay(g, 'o3')).toEqual({ text: 'Err', isError: true, isRef: false })
  })

  it('unknown ids display as empty text', () => {
    expect(fieldDisplay(graphOf([]), 'nope')).toEqual({ text: '', isError: false, isRef: false })
  })
})

// --- resolveFieldPlaceholders (slice 6, #34) ------------------------------------------------

describe('resolveFieldPlaceholders — fields inside LaTeX, output-as-input rule', () => {
  it('[input:x] substitutes German-formatted values (space grouping, decimal comma)', () => {
    const { graph } = mutableGraphOf([
      input('rev', 'Revenue', '1200'),
      input('mar', 'Margin', '0.2534'),
    ])
    expect(resolveFieldPlaceholders(graph, 'x = [input:Revenue] + [input:Margin]')).toBe(
      'x = 1 200 + 0,2534'
    )
  })

  it('unknown names stay literal; display prettification still applies around them', () => {
    const { graph, writes } = mutableGraphOf([])
    expect(resolveFieldPlaceholders(graph, '[input:Nope]*2')).toBe('[input:Nope]\\,\\cdot\\,2')
    expect(resolveFieldPlaceholders(graph, '[output:Nope]')).toBe('[output:Nope]')
    expect(writes).toEqual([])
  })

  it('[output:x] is the calculation target of its formula line and persists latexValue', () => {
    const ebit = output('ebit', 'EBIT', '')
    const { graph, writes } = mutableGraphOf([
      input('rev', 'Revenue', '1200'),
      input('mar', 'Margin', '0.2534'),
      ebit,
    ])
    const raw =
      '\\begin{aligned}EBIT &= [input:Revenue] * [input:Margin] = [output:EBIT]\\end{aligned}'
    expect(resolveFieldPlaceholders(graph, raw)).toBe(
      '\\begin{aligned}EBIT &= 1 200 \\,\\cdot\\, 0,2534 = 304,08\\end{aligned}'
    )
    // Raw String(v) write-back, floating-point noise included (reference parity).
    expect(ebit.latexValue).toBe('304.08000000000004')
    expect(writes.map((w) => w.id)).toEqual(['ebit'])
  })

  it('output-as-input rule: [input:EBIT] reads the STORED value — formula 2 never overwrites EBIT', () => {
    const rev = input('rev', 'Revenue', '1200')
    const ebit = output('ebit', 'EBIT', '')
    const tax = output('tax', 'Tax', '')
    const { graph, writes } = mutableGraphOf([rev, input('mar', 'Margin', '0.2534'), ebit, tax])
    const raw1 =
      '\\begin{aligned}EBIT &= [input:Revenue] * [input:Margin] = [output:EBIT]\\end{aligned}'
    const raw2 = 'Tax = [input:EBIT] * 0,3 = [output:Tax]'
    resolveFieldPlaceholders(graph, raw1)

    expect(resolveFieldPlaceholders(graph, raw2)).toBe('Tax = 304,08 \\,\\cdot\\, 0,3 = 91,22')
    expect(tax.latexValue).toBe('91.224')
    expect(ebit.latexValue).toBe('304.08000000000004') // untouched by formula 2
    expect(writes.map((w) => w.id)).toEqual(['ebit', 'tax']) // no second EBIT write

    // Propagation: Revenue changes, the chain re-resolves in document order.
    rev.value = '2000'
    expect(resolveFieldPlaceholders(graph, raw1)).toBe(
      '\\begin{aligned}EBIT &= 2 000 \\,\\cdot\\, 0,2534 = 506,8\\end{aligned}'
    )
    expect(ebit.latexValue).toBe('506.8')
    expect(resolveFieldPlaceholders(graph, raw2)).toBe('Tax = 506,8 \\,\\cdot\\, 0,3 = 152,04')
    expect(tax.latexValue).toBe('152.04')
  })

  it('write-backs are visible to later placeholders in the SAME pass', () => {
    const a = output('a', 'A', '')
    const b = output('b', 'B', '')
    const { graph } = mutableGraphOf([a, b])
    expect(
      resolveFieldPlaceholders(graph, '2+3=[output:A] \\\\ B = [input:A]+1 = [output:B]')
    ).toBe('2+3=5 \\\\ B = 5+1 = 6')
    expect(a.latexValue).toBe('5')
    expect(b.latexValue).toBe('6')
  })

  it('a non-finite target renders \\text{Err} and CLEARS the stored latexValue', () => {
    const a = output('a', 'A', '', '5')
    const { graph, writes } = mutableGraphOf([a])
    // No "=" before the placeholder → empty auto-expression → NaN.
    expect(resolveFieldPlaceholders(graph, '[output:A]')).toBe('\\text{Err}')
    expect(a.latexValue).toBeUndefined()
    expect(writes).toEqual([{ id: 'a', v: NaN }])
  })

  it('[output:x] with a MANUAL expression is a value reference — no write-back', () => {
    const c = output('c', 'C', '2*3')
    const { graph, writes } = mutableGraphOf([c])
    expect(resolveFieldPlaceholders(graph, 'x = [output:C]')).toBe('x = 6')
    expect(resolveFieldPlaceholders(graph, 'x = [input:C]')).toBe('x = 6')
    expect(writes).toEqual([])
    expect(c.latexValue).toBeUndefined()
  })

  it('quirk: [output:x] naming an INPUT reads the input value (reference branch)', () => {
    const { graph, writes } = mutableGraphOf([input('rev', 'Revenue', '1200')])
    expect(resolveFieldPlaceholders(graph, '[output:Revenue]')).toBe('1 200')
    expect(writes).toEqual([])
  })

  it('[input:x] on an output without stored value falls back to getFieldValue', () => {
    // Hidden store: no line context, no latexValue → Err.
    const { graph } = mutableGraphOf([output('h', 'H', '')])
    expect(resolveFieldPlaceholders(graph, '[input:H]')).toBe('\\text{Err}')

    // With a text-line context the ":"-rule of the main editor applies.
    const h2 = output('h2', 'H2', '')
    const { graph: g2 } = mutableGraphOf([h2], { h2: toks('Summe: 2+4*3 = §1', { 1: 'h2' }) })
    expect(resolveFieldPlaceholders(g2, '[input:H2]')).toBe('14')
  })

  it('a pre-populated visited set renders \\text{Err} (recursion guard)', () => {
    const { graph } = mutableGraphOf([input('rev', 'Revenue', '1200')])
    expect(resolveFieldPlaceholders(graph, '[input:Revenue]', new Set(['rev']))).toBe(
      '\\text{Err}'
    )
  })

  it('graph cycles through placeholders collapse to 0 (reference quirk); unresolvable inputs → Err', () => {
    const { graph } = mutableGraphOf([
      refInput('ci', 'cycIn', 'co'),
      output('co', 'cycOut', 'cycIn'),
    ])
    expect(resolveFieldPlaceholders(graph, '[input:cycIn]')).toBe('0')
    expect(resolveFieldPlaceholders(graph, '[output:cycOut]')).toBe('0')

    const { graph: g2 } = mutableGraphOf([input('l', 'leer', '')])
    expect(resolveFieldPlaceholders(g2, '[input:leer]')).toBe('\\text{Err}')
  })

  it('graphs without setLatexValue still resolve (write-back is optional)', () => {
    const g = graphOf([input('rev', 'Revenue', '1200'), output('ebit', 'EBIT', '')])
    expect(resolveFieldPlaceholders(g, 'x = [input:Revenue]*2 = [output:EBIT]')).toBe(
      'x = 1 200\\,\\cdot\\,2 = 2 400'
    )
  })
})
