/**
 * Input/Output field graph resolution for the LaTeX editor (PRD #28,
 * slice 5 — #33).
 *
 * Faithful port of the standalone editor's CONSOLIDATED (last-wins) field
 * system (reference file
 * latexEditor/latex_editor_FIXED_JSON_IMPORT_COMPLETE_OUTPUT_AS_INPUT_LATEX_FIX.htm.html):
 * - `getFieldValue` ← the FINAL PATCH wrapper (L2153–2164) with the base
 *   version (L1475–1495) inlined. Parity quirks preserved: the stored
 *   `latexValue` short-circuit runs BEFORE the visited check and does NOT
 *   join the visited set (an output carrying a stored LaTeX value escapes
 *   cycle marking); the visited set is MUTATED down reference chains, while
 *   auto-expression tokens and name substitution receive fresh copies.
 * - `autoExpressionForOutput` ← the base `getAutoExpression` (L1529–1562),
 *   the only definition — the ":"-rule for text lines lives here. The DOM
 *   line walk (`tokenizeLine`) stays in the controller adapter; this module
 *   sees only the token list. Quirk preserved: the output's position is the
 *   FIRST token with its field id, so a clone earlier in the same line wins.
 * - `evalFieldExpression` ← the FINAL PATCH `evalExpression` (L2250–2255),
 *   superseding the base version (L1564): LaTeX normalisation first, then
 *   variable-name substitution (valid identifiers only, longest name first,
 *   once per name, `\b`-bounded, non-finite → `(0)`), then the CSP-safe
 *   evaluator instead of `new Function`.
 * - `getFieldByName` ← base L1470 (first match in document order).
 * - `findDuplicateName` ← the unique-name patch's `dup()` (L2653).
 * - `classifyTypedPlaceholder` ← the conversion decision inside the FINAL
 *   PATCH `convertTypedFieldPlaceholders` (L2284): the typed kind must match
 *   the field's type, otherwise the placeholder stays literal text.
 * - `fieldDisplay` ← the base `updateAllFields` per-field logic (L1624–1646)
 *   with the FINAL PATCH extension (L2288–2295) folded in — the extension's
 *   fixups are redundant once `getFieldValue` carries the `latexValue`
 *   short-circuit, so a single pass reproduces the composed behavior.
 *   Parity: STATIC inputs display their raw value string (`value || '0'`,
 *   e.g. `1000` and `2.5` stay unformatted); only computed values
 *   (references, outputs) go through the German `formatValue`.
 *
 * Cycle semantics (goldens generated by executing the reference composition
 * in Node): visited sets guarantee termination, but name/token cycles
 * collapse to `(0)` inside expressions — the display result is usually 0,
 * not „Err". „Err" appears when the resolved value is non-finite: empty
 * auto-expressions (no `=` before the output), invalid expressions, unknown
 * names.
 *
 * `resolveFieldPlaceholders` (fields inside LaTeX, output-as-input rule,
 * reference L2698) is slice 6 (#34) and will join this module.
 *
 * Operates on plain field objects behind the {@link FieldGraph} adapter —
 * pure and DOM-free, reusable by the future student-facing renderer.
 */

import { evaluateExpression } from './expression-evaluator'
import { normaliseLatexForEvaluation } from './latex-normalise'
import { formatValue } from './number-format'

/** Plain snapshot of a field pill's configuration (mirrors its `dataset`). */
export interface FieldData {
  id: string
  type: 'input' | 'output'
  /** `''` when unnamed. */
  name: string
  /** Inputs only. */
  refType?: 'static' | 'ref'
  /** Inputs (static): the raw value string — `parseFloat` semantics apply. */
  value?: string
  /** Inputs (ref): field id of the referenced Output. */
  refId?: string
  /** Outputs: manual expression override (`''` → auto-expression). */
  expr?: string
  /** Outputs: value persisted by a LaTeX `[output:x]` resolution (slice 6). */
  latexValue?: string
}

/**
 * One token of a text line, in document order: a single character or a field
 * pill (the reference's `tokenizeLine`, L1507–1524, walks the DOM to build
 * this; the controller's adapter does the same).
 */
export type LineToken = { char: string } | { fieldId: string }

/** Thin adapter over the live document — the controller implements it on DOM. */
export interface FieldGraph {
  /** First field with this id in document order (clones share ids). */
  byId(id: string): FieldData | null
  /** All fields in document order, clones included. */
  all(): FieldData[]
  /**
   * Tokens of the line (top-level block) containing the field's first
   * instance, or `null` when there is no text-line context (unknown field,
   * hidden store).
   */
  lineTokensFor(fieldId: string): LineToken[] | null
}

function storedLatexValue(el: FieldData): number {
  if (el.type !== 'output' || el.latexValue === undefined) return NaN
  const v = parseFloat(el.latexValue)
  return Number.isFinite(v) ? v : NaN
}

/**
 * Resolves a field's current numeric value (NaN when unresolvable). The
 * `visited` set is the cycle guard; callers passing it explicitly must
 * expect it to be mutated (reference parity).
 */
export function getFieldValue(
  graph: FieldGraph,
  id: string,
  visited: Set<string> = new Set()
): number {
  // FINAL PATCH short-circuit (L2156–2163): runs before the visited check.
  const el = graph.byId(id)
  if (el && el.type === 'output' && !(el.expr || '').trim()) {
    const sv = storedLatexValue(el)
    if (Number.isFinite(sv)) return sv
  }
  // Base version (L1475–1495).
  if (visited.has(id)) return NaN
  visited.add(id)
  if (!el) return NaN
  if (el.type === 'input') {
    if (el.refType === 'ref' && el.refId) {
      return getFieldValue(graph, el.refId, visited)
    }
    return parseFloat(el.value ?? '')
  }
  // Output.
  let expr = el.expr || ''
  if (!expr.trim()) {
    expr = autoExpressionForOutput(graph, id, visited)
  }
  return evalFieldExpression(graph, expr, visited)
}

/**
 * Derives an Output's expression from its line: the segment between the
 * nearest `=` BEFORE the output pill and the last `:` or `=` before that
 * (else the line start). Field tokens are substituted by their values as
 * `(value)` / `(0)`. Returns `''` when there is no line context or no `=`
 * before the pill — which evaluates to NaN → „Err".
 */
export function autoExpressionForOutput(
  graph: FieldGraph,
  outputId: string,
  visited: Set<string> = new Set()
): string {
  const tokens = graph.lineTokensFor(outputId)
  if (!tokens) return ''
  const outputIndex = tokens.findIndex((t) => 'fieldId' in t && t.fieldId === outputId)
  if (outputIndex === -1) return ''

  // Nächstes "=" VOR dem Output-Feld suchen (schließt die Formel ab)
  let eqIndex = -1
  for (let i = outputIndex - 1; i >= 0; i--) {
    const t = tokens[i]
    if ('char' in t && t.char === '=') {
      eqIndex = i
      break
    }
  }
  if (eqIndex === -1) return ''

  // Startgrenze davor suchen: letztes ":" oder "=" VOR diesem "=", sonst Zeilenanfang
  let startIndex = 0
  for (let i = eqIndex - 1; i >= 0; i--) {
    const t = tokens[i]
    if ('char' in t && (t.char === ':' || t.char === '=')) {
      startIndex = i + 1
      break
    }
  }

  let expr = ''
  for (let i = startIndex; i < eqIndex; i++) {
    const tok = tokens[i]
    if ('fieldId' in tok) {
      const v = getFieldValue(graph, tok.fieldId, new Set(visited))
      expr += Number.isFinite(v) ? '(' + v + ')' : '(0)'
    } else {
      expr += tok.char
    }
  }
  return expr.trim()
}

/**
 * Evaluates an expression in the context of the field graph: LaTeX
 * normalisation, then variable-name substitution, then the CSP-safe
 * evaluator. Any failure yields NaN.
 */
export function evalFieldExpression(
  graph: FieldGraph,
  expr: string,
  visited: Set<string> = new Set()
): number {
  if (!expr || !expr.trim()) return NaN
  let p = normaliseLatexForEvaluation(expr)

  // Variablen-Namen durch Werte ersetzen (längste zuerst, einmal pro Name).
  const named = graph
    .all()
    .filter((el) => el.name && /^[a-zA-Z_]\w*$/.test(el.name))
    .sort((a, b) => b.name.length - a.name.length)
  const seen = new Set<string>()
  for (const el of named) {
    const n = el.name
    if (seen.has(n)) continue
    seen.add(n)
    const re = new RegExp('\\b' + n + '\\b', 'g')
    if (re.test(p)) {
      const v = getFieldValue(graph, el.id, new Set(visited))
      p = p.replace(re, Number.isFinite(v) ? '(' + v + ')' : '(0)')
    }
  }
  return evaluateExpression(p)
}

/** First field with this exact name in document order (base L1470). */
export function getFieldByName(graph: FieldGraph, name: string): FieldData | null {
  if (!name) return null
  return graph.all().find((el) => el.name === name) ?? null
}

/**
 * Unique-name enforcement (patch L2653): case-insensitive, trimmed; clones
 * of the edited field (same id) never count; empty names are never
 * duplicates. Returns the conflicting field or `null`.
 */
export function findDuplicateName(
  graph: FieldGraph,
  name: string,
  currentId: string
): FieldData | null {
  const target = (name || '').trim().toLowerCase()
  if (!target) return null
  const seen = new Set<string>()
  for (const f of graph.all()) {
    const id = f.id || ''
    if (!id || id === currentId || seen.has(id)) continue
    seen.add(id)
    if ((f.name || '').trim().toLowerCase() === target) return f
  }
  return null
}

/**
 * Decision of the typed-placeholder sweep (`[input:x]` / `[output:x]` in
 * plain text): the typed kind must match the field's actual type —
 * `[output:x]` on an Output becomes a reference pill, `[input:x]` on an
 * Input becomes a visible clone, everything else stays literal text.
 */
export function classifyTypedPlaceholder(
  kind: 'input' | 'output',
  field: FieldData | null
): 'visible-input-clone' | 'output-reference' | 'keep-text' {
  if (!field) return 'keep-text'
  if (kind === 'output' && field.type === 'output') return 'output-reference'
  if (kind === 'input' && field.type === 'input') return 'visible-input-clone'
  return 'keep-text'
}

/** What a field pill must display (consolidated `updateAllFields` per-field logic). */
export interface FieldDisplay {
  text: string
  isError: boolean
  isRef: boolean
}

/** Display state for one field: raw string for static inputs, German-formatted values for references and outputs, „Err" for non-finite outputs. */
export function fieldDisplay(graph: FieldGraph, id: string): FieldDisplay {
  const el = graph.byId(id)
  if (!el) return { text: '', isError: false, isRef: false }
  if (el.type === 'input') {
    if (el.refType === 'ref' && el.refId) {
      return { text: formatValue(getFieldValue(graph, id)), isError: false, isRef: true }
    }
    return { text: el.value || '0', isError: false, isRef: false }
  }
  const v = getFieldValue(graph, id)
  if (!Number.isFinite(v)) return { text: 'Err', isError: true, isRef: false }
  return { text: formatValue(v), isError: false, isRef: false }
}
