/**
 * Input/Output field graph resolution for the LaTeX editor (PRD #28,
 * slice 5 — #33).
 *
 * Faithful port of the standalone editor's CONSOLIDATED (last-wins) field
 * system (reference file
 * latexEditor/latex_editor_FIXED_JSON_IMPORT_COMPLETE_OUTPUT_AS_INPUT_LATEX_FIX.htm.html):
 * - `getFieldValue` ← the FINAL PATCH wrapper (L2153–2164) with the base
 *   version (L1475–1495) inlined. Parity quirks preserved: the stored
 *   `latexValue` short-circuit runs BEFORE the visited check and does NOT
 *   join the visited set (an output carrying a stored LaTeX value escapes
 *   cycle marking); the visited set is MUTATED down reference chains, while
 *   auto-expression tokens and name substitution receive fresh copies.
 * - `autoExpressionForOutput` ← the base `getAutoExpression` (L1529–1562),
 *   the only definition — the ":"-rule for text lines lives here. The DOM
 *   line walk (`tokenizeLine`) stays in the controller adapter; this module
 *   sees only the token list. Quirk preserved: the output's position is the
 *   FIRST token with its field id, so a clone earlier in the same line wins.
 * - `evalFieldExpression` ← the FINAL PATCH `evalExpression` (L2250–2255),
 *   superseding the base version (L1564): LaTeX normalisation first, then
 *   variable-name substitution (valid identifiers only, longest name first,
 *   once per name, `\b`-bounded, non-finite → `(0)`), then the CSP-safe
 *   evaluator instead of `new Function`.
 * - `getFieldByName` ← base L1470 (first match in document order).
 * - `findDuplicateName` ← the unique-name patch's `dup()` (L2653).
 * - `classifyTypedPlaceholder` ← the conversion decision inside the FINAL
 *   PATCH `convertTypedFieldPlaceholders` (L2284): the typed kind must match
 *   the field's type, otherwise the placeholder stays literal text.
 * - `fieldDisplay` ← the base `updateAllFields` per-field logic (L1624–1646)
 *   with the FINAL PATCH extension (L2288–2295) folded in — the extension's
 *   fixups are redundant once `getFieldValue` carries the `latexValue`
 *   short-circuit, so a single pass reproduces the composed behavior.
 *   Parity: STATIC inputs display their raw value string (`value || '0'`,
 *   e.g. `1000` and `2.5` stay unformatted); only computed values
 *   (references, outputs) go through the German `formatValue`.
 *
 * Cycle semantics (goldens generated by executing the reference composition
 * in Node): visited sets guarantee termination, but name/token cycles
 * collapse to `(0)` inside expressions — the display result is usually 0,
 * not „Err". „Err" appears when the resolved value is non-finite: empty
 * auto-expressions (no `=` before the output), invalid expressions, unknown
 * names.
 *
 * Slice 6 (#34) adds `resolveFieldPlaceholders` ← the FINAL patch layer
 * (`patch-output-as-input-latex-fix-v1`, L2698–2728), which fully replaces
 * the base (L912) and intermediate (L2270) versions and SUBSUMES the
 * standalone `\cdot` display patch (L2641) by ending with
 * `prettifyMultiplicationStars`. Consolidation notes:
 * - The reference's `getStoredOrCalculatedValueAsReference` (L2684) collapses
 *   into `getFieldValue` — its stored-`latexValue` short-circuit is already
 *   `getFieldValue`'s first step (before the visited check).
 * - The `[output:x]` write-back (the reference mutates `el.dataset.latexValue`,
 *   pill text and `is-error` class in place, L2710–2717) goes through the
 *   optional {@link FieldGraph.setLatexValue} seam. The mutation MUST be
 *   visible to subsequent `byId`/`all` reads mid-pass: a later `[input:A]` in
 *   the same raw string sees an earlier `[output:A]`'s fresh value, exactly
 *   like the reference's live DOM.
 *
 * Operates on plain field objects behind the {@link FieldGraph} adapter —
 * pure and DOM-free, reusable by the future student-facing renderer.
 */

import { evaluateExpression } from './expression-evaluator'
import { prettifyMultiplicationStars } from './latex-display'
import {
  getAutoExpressionFromLatexText,
  normaliseLatexForEvaluation,
  type PlaceholderResolver,
} from './latex-normalise'
import { formatValue } from './number-format'

/** Plain snapshot of a field pill's configuration (mirrors its `dataset`). */
export interface FieldData {
  id: string
  type: 'input' | 'output'
  /** `''` when unnamed. */
  name: string
  /** Inputs only. */
  refType?: 'static' | 'ref'
  /** Inputs (static): the raw value string — `parseFloat` semantics apply. */
  value?: string
  /** Inputs (ref): field id of the referenced Output. */
  refId?: string
  /** Outputs: manual expression override (`''` → auto-expression). */
  expr?: string
  /** Outputs: value persisted by a LaTeX `[output:x]` resolution (raw `String(v)`). */
  latexValue?: string
}

/**
 * One token of a text line, in document order: a single character or a field
 * pill (the reference's `tokenizeLine`, L1507–1524, walks the DOM to build
 * this; the controller's adapter does the same).
 */
export type LineToken = { char: string } | { fieldId: string }

/** Thin adapter over the live document — the controller implements it on DOM. */
export interface FieldGraph {
  /** First field with this id in document order (clones share ids). */
  byId(id: string): FieldData | null
  /** All fields in document order, clones included. */
  all(): FieldData[]
  /**
   * Tokens of the line (top-level block) containing the field's first
   * instance, or `null` when there is no text-line context (unknown field,
   * hidden store).
   */
  lineTokensFor(fieldId: string): LineToken[] | null
  /**
   * Write-back of an `[output:x]` calculation-target result (reference
   * L2710–2717): finite `v` → persist `String(v)` as the field's
   * `latexValue` (the DOM adapter also sets the pill text to `formatValue(v)`
   * and clears `is-error`); non-finite → clear `latexValue` (pill shows
   * „Err"). Optional so read-only graphs stay valid; the write must be
   * visible to subsequent `byId`/`all` reads within the same resolution pass.
   */
  setLatexValue?(fieldId: string, v: number): void
}

function storedLatexValue(el: FieldData): number {
  if (el.type !== 'output' || el.latexValue === undefined) return NaN
  const v = parseFloat(el.latexValue)
  return Number.isFinite(v) ? v : NaN
}

/**
 * Resolves a field's current numeric value (NaN when unresolvable). The
 * `visited` set is the cycle guard; callers passing it explicitly must
 * expect it to be mutated (reference parity).
 */
export function getFieldValue(
  graph: FieldGraph,
  id: string,
  visited: Set<string> = new Set()
): number {
  // FINAL PATCH short-circuit (L2156–2163): runs before the visited check.
  const el = graph.byId(id)
  if (el && el.type === 'output' && !(el.expr || '').trim()) {
    const sv = storedLatexValue(el)
    if (Number.isFinite(sv)) return sv
  }
  // Base version (L1475–1495).
  if (visited.has(id)) return NaN
  visited.add(id)
  if (!el) return NaN
  if (el.type === 'input') {
    if (el.refType === 'ref' && el.refId) {
      return getFieldValue(graph, el.refId, visited)
    }
    return parseFloat(el.value ?? '')
  }
  // Output.
  let expr = el.expr || ''
  if (!expr.trim()) {
    expr = autoExpressionForOutput(graph, id, visited)
  }
  return evalFieldExpression(graph, expr, visited)
}

/**
 * Derives an Output's expression from its line: the segment between the
 * nearest `=` BEFORE the output pill and the last `:` or `=` before that
 * (else the line start). Field tokens are substituted by their values as
 * `(value)` / `(0)`. Returns `''` when there is no line context or no `=`
 * before the pill — which evaluates to NaN → „Err".
 */
export function autoExpressionForOutput(
  graph: FieldGraph,
  outputId: string,
  visited: Set<string> = new Set()
): string {
  const tokens = graph.lineTokensFor(outputId)
  if (!tokens) return ''
  const outputIndex = tokens.findIndex((t) => 'fieldId' in t && t.fieldId === outputId)
  if (outputIndex === -1) return ''

  // Nächstes "=" VOR dem Output-Feld suchen (schließt die Formel ab)
  let eqIndex = -1
  for (let i = outputIndex - 1; i >= 0; i--) {
    const t = tokens[i]
    if ('char' in t && t.char === '=') {
      eqIndex = i
      break
    }
  }
  if (eqIndex === -1) return ''

  // Startgrenze davor suchen: letztes ":" oder "=" VOR diesem "=", sonst Zeilenanfang
  let startIndex = 0
  for (let i = eqIndex - 1; i >= 0; i--) {
    const t = tokens[i]
    if ('char' in t && (t.char === ':' || t.char === '=')) {
      startIndex = i + 1
      break
    }
  }

  let expr = ''
  for (let i = startIndex; i < eqIndex; i++) {
    const tok = tokens[i]
    if ('fieldId' in tok) {
      const v = getFieldValue(graph, tok.fieldId, new Set(visited))
      expr += Number.isFinite(v) ? '(' + v + ')' : '(0)'
    } else {
      expr += tok.char
    }
  }
  return expr.trim()
}

/**
 * Evaluates an expression in the context of the field graph: LaTeX
 * normalisation, then variable-name substitution, then the CSP-safe
 * evaluator. Any failure yields NaN.
 */
export function evalFieldExpression(
  graph: FieldGraph,
  expr: string,
  visited: Set<string> = new Set()
): number {
  if (!expr || !expr.trim()) return NaN
  let p = normaliseLatexForEvaluation(expr)

  // Variablen-Namen durch Werte ersetzen (längste zuerst, einmal pro Name).
  const named = graph
    .all()
    .filter((el) => el.name && /^[a-zA-Z_]\w*$/.test(el.name))
    .sort((a, b) => b.name.length - a.name.length)
  const seen = new Set<string>()
  for (const el of named) {
    const n = el.name
    if (seen.has(n)) continue
    seen.add(n)
    const re = new RegExp('\\b' + n + '\\b', 'g')
    if (re.test(p)) {
      const v = getFieldValue(graph, el.id, new Set(visited))
      p = p.replace(re, Number.isFinite(v) ? '(' + v + ')' : '(0)')
    }
  }
  return evaluateExpression(p)
}

/** First field with this exact name in document order (base L1470). */
export function getFieldByName(graph: FieldGraph, name: string): FieldData | null {
  if (!name) return null
  return graph.all().find((el) => el.name === name) ?? null
}

/**
 * Unique-name enforcement (patch L2653): case-insensitive, trimmed; clones
 * of the edited field (same id) never count; empty names are never
 * duplicates. Returns the conflicting field or `null`.
 */
export function findDuplicateName(
  graph: FieldGraph,
  name: string,
  currentId: string
): FieldData | null {
  const target = (name || '').trim().toLowerCase()
  if (!target) return null
  const seen = new Set<string>()
  for (const f of graph.all()) {
    const id = f.id || ''
    if (!id || id === currentId || seen.has(id)) continue
    seen.add(id)
    if ((f.name || '').trim().toLowerCase() === target) return f
  }
  return null
}

/**
 * Decision of the typed-placeholder sweep (`[input:x]` / `[output:x]` in
 * plain text): the typed kind must match the field's actual type —
 * `[output:x]` on an Output becomes a reference pill, `[input:x]` on an
 * Input becomes a visible clone, everything else stays literal text.
 */
export function classifyTypedPlaceholder(
  kind: 'input' | 'output',
  field: FieldData | null
): 'visible-input-clone' | 'output-reference' | 'keep-text' {
  if (!field) return 'keep-text'
  if (kind === 'output' && field.type === 'output') return 'output-reference'
  if (kind === 'input' && field.type === 'input') return 'visible-input-clone'
  return 'keep-text'
}

/** What a field pill must display (consolidated `updateAllFields` per-field logic). */
export interface FieldDisplay {
  text: string
  isError: boolean
  isRef: boolean
}

/** Display state for one field: raw string for static inputs, German-formatted values for references and outputs, „Err" for non-finite outputs. */
export function fieldDisplay(graph: FieldGraph, id: string): FieldDisplay {
  const el = graph.byId(id)
  if (!el) return { text: '', isError: false, isRef: false }
  if (el.type === 'input') {
    if (el.refType === 'ref' && el.refId) {
      return { text: formatValue(getFieldValue(graph, id)), isError: false, isRef: true }
    }
    return { text: el.value || '0', isError: false, isRef: false }
  }
  const v = getFieldValue(graph, id)
  if (!Number.isFinite(v)) return { text: 'Err', isError: true, isRef: false }
  return { text: formatValue(v), isError: false, isRef: false }
}

/**
 * Resolves `[input:x]`/`[output:x]` placeholders in a raw LaTeX string to
 * display values — the FINAL patch layer's output-as-input rule (reference
 * L2698–2728):
 *
 * - `[output:x]` on an Output WITHOUT a manual expression is the
 *   **calculation target** of its formula line: the expression is derived
 *   offset-based from the raw LaTeX itself (`getAutoExpressionFromLatexText`),
 *   evaluated, and written back via {@link FieldGraph.setLatexValue} —
 *   finite results persist as `latexValue`, non-finite results clear it.
 * - Everything else is **always a value reference** — `[input:x]` even when
 *   `x` is an Output variable (that is the output-as-input fix: editing a
 *   later formula never overwrites an earlier output), `[output:x]` with a
 *   manual expression, and the quirk `[output:x]` naming an Input. No
 *   write-back ever happens on this branch.
 * - Unknown names keep the literal placeholder (visible in the rendered
 *   code); fields already in `visited` render as `\text{Err}`; non-finite
 *   values render as `\text{Err}`.
 * - The final string is display-prettified (`*` → `\,\cdot\,`), which is how
 *   the final layer subsumed the standalone `\cdot` patch.
 *
 * Replacement values are the German `formatValue` strings (space-grouped
 * thousands, decimal comma) embedded verbatim in the LaTeX — reference
 * parity. Write-backs happen mid-pass, so later placeholders in the same
 * string see earlier `[output:x]` results.
 */
export function resolveFieldPlaceholders(
  graph: FieldGraph,
  rawLatex: string,
  visited: Set<string> = new Set()
): string {
  // Nested placeholders inside an auto-expression segment resolve as VALUES
  // with the OUTER visited set (reference normaliseAutoExpressionText,
  // L2259): unknown or already-visited fields → null → '0' in the segment.
  const resolveNested: PlaceholderResolver = (_kind, name) => {
    const f = getFieldByName(graph, name)
    if (!f) return null
    if (visited.has(f.id)) return null
    return getFieldValue(graph, f.id, new Set(visited))
  }

  const resolved = (rawLatex || '').replace(
    /\[(input|output):([^\]]+)\]/g,
    (match, kind: string, name: string, offset: number) => {
      const el = getFieldByName(graph, (name || '').trim())
      if (!el) return match // unbekannter Name: unverändert lassen, sichtbar im Code
      if (visited.has(el.id)) return '\\text{Err}'

      let v: number
      if (kind === 'output' && el.type === 'output' && !(el.expr || '').trim()) {
        // Nur ein explizites [output:Name] darf den Output aus der aktuellen
        // LaTeX-Formel berechnen/aktualisieren (L2706–2718).
        const expr = getAutoExpressionFromLatexText(rawLatex, offset, resolveNested)
        v = evalFieldExpression(graph, expr, new Set(visited).add(el.id))
        graph.setLatexValue?.(el.id, v)
      } else {
        // [input:Name] ist immer eine Referenz/Lese-Operation — auch wenn
        // Name zu einer Output-Variable gehört (L2719–2723). The reference's
        // getStoredOrCalculatedValueAsReference collapses into getFieldValue:
        // its stored-latexValue short-circuit is already getFieldValue's
        // first step.
        v = getFieldValue(graph, el.id, new Set(visited))
      }
      return Number.isFinite(v) ? formatValue(v) : '\\text{Err}'
    }
  )
  return prettifyMultiplicationStars(resolved)
}
