/**
 * Golden parity tests for latex-normalise (#30).
 *
 * Every expected value was generated by executing the standalone editor's
 * FINAL patched functions (`normaliseLatexForEvaluation`,
 * `getAutoExpressionFromLatexText`, `normaliseAutoExpressionText` — reference
 * file lines 2238–2268) in Node — these tests are the port's parity contract,
 * quirks included.
 */
import { describe, expect, it } from 'vitest'
import {
  getAutoExpressionFromLatexText,
  normaliseAutoExpressionText,
  normaliseLatexForEvaluation,
  type PlaceholderResolver,
} from './latex-normalise'

describe('normaliseLatexForEvaluation', () => {
  describe('\\frac (balanced-brace, nested)', () => {
    it.each<[string, string]>([
      ['\\frac{1}{2}', '((1)/(2))'],
      ['\\frac{\\frac{1}{2}}{3}', '((((1)/(2)))/(3))'],
      ['\\frac { a } { b }', '(( a )/( b ))'],
      // Unbalanced braces keep the token; braces become parens afterwards.
      ['\\frac{1}', '\\frac(1)'],
      ['\\frac{a}{b} \\cdot 100', '((a)/(b)) * 100'],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })

  describe('\\sqrt', () => {
    it.each<[string, string]>([
      ['\\sqrt{16}', 'sqrt(16)'],
      ['\\sqrt{\\frac{a}{b}}', 'sqrt(((a)/(b)))'],
      // Without a braced argument the token survives and the whitespace
      // after it is dropped (quirk preserved from the original).
      ['\\sqrt 2', '\\sqrt2'],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })

  describe('symbol and function-name mapping', () => {
    it.each<[string, string]>([
      ['2\\cdot3', '2*3'],
      ['2 \\times 3', '2 * 3'],
      ['a\\div b', 'a/ b'],
      ['\\pi', 'pi'],
      ['2\\pi r', '2pi r'],
      ['\\sin{x}', 'sin(x)'],
      ['\\cos(x)', 'cos(x)'],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })

  describe('whitespace commands, \\left/\\right, text-family unwrapping', () => {
    it.each<[string, string]>([
      ['1\\,000', '1 000'],
      ['a\\quad b', 'a  b'],
      ['x~y', 'x y'],
      ['\\left(\\frac{1}{2}\\right)', '(((1)/(2)))'],
      ['\\text{Kosten}', 'Kosten'],
      ['\\mathrm{kg}', 'kg'],
      ['\\operatorname {foo}', 'foo'],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })

  describe('environments and alignment', () => {
    it('flattens \\begin/\\end, \\\\ and & to spaces', () => {
      expect(normaliseLatexForEvaluation('\\begin{aligned}a &= 2 \\\\ b &= 3\\end{aligned}')).toBe(
        ' a  = 2   b  = 3 ',
      )
    })
  })

  describe('decimal commas', () => {
    it.each<[string, string]>([
      ['3,14', '3.14'],
      ['1,5 + 2,5', '1.5 + 2.5'],
      // Single-pass replacement: consecutive comma groups only convert the
      // first (quirk preserved from the original).
      ['1,2,3', '1.2,3'],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })

  describe('exponent and brace conversion', () => {
    it.each<[string, string]>([
      ['2^{10}', '2**(10)'],
      ['x^2 + y^2', 'x**2 + y**2'],
      ['', ''],
    ])('%j → %j', (input, expected) => {
      expect(normaliseLatexForEvaluation(input)).toBe(expected)
    })
  })
})

// Map-based stand-in for the field graph: `cyc` simulates a field already in
// the caller's visited set (the resolver returns null for cycles and unknown
// names alike), `bad` a field whose value is non-finite.
const values: Record<string, number> = { a: 2, b: 3, Umsatz: 1200, Marge: 0.25, bad: NaN }
const resolve: PlaceholderResolver = (_kind, name) => {
  if (name === 'cyc') return null
  return name in values ? values[name] : null
}

describe('normaliseAutoExpressionText', () => {
  it.each<[string, string]>([
    [' 2 + 3 ', '2 + 3'],
    ['a & b', 'a   b'],
    ['\\begin{aligned}x\\end{aligned}', 'x'],
    // finite values → '(v)'
    ['[input:a]*[input:b]', '(2)*(3)'],
    // \\ row breaks (with optional [gap] argument) become spaces
    ['\\\\[2mm] x', 'x'],
    // unknown/cycle → '0', non-finite → '(0)'
    ['[input:unknown] + [input:cyc] + [input:bad]', '0 + 0 + (0)'],
  ])('%j → %j', (input, expected) => {
    expect(normaliseAutoExpressionText(input, resolve)).toBe(expected)
  })
})

describe('getAutoExpressionFromLatexText', () => {
  /** Extracts for the first [output:…] placeholder, like the original call sites. */
  function extract(rawLatex: string): string {
    return getAutoExpressionFromLatexText(rawLatex, rawLatex.indexOf('[output:'), resolve)
  }

  it.each<[string, string]>([
    // one '=' with a non-label before-part → text before the '='
    ['2+3 = [output:S]', '2+3'],
    // two '=' → text between the last two '='
    ['K = 2*3 = [output:K]', '2*3'],
    // one '=', label before-part but nothing after the '=' → falls back to the label text
    ['Kosten = [output:K]', 'Kosten'],
    // one '=', label before-part with content after the '=' → text after the '='
    ['E = 2*[input:a][output:x]', '2*(2)'],
    // '\n' bounds the line: the first line's '=' must not leak in
    ['x = 1\ny = 2*2 = [output:y]', '2*2'],
    // '\\' bounds the line, but line start lands on the SECOND backslash,
    // so a stray '\' survives in the segment (quirk preserved).
    ['a = 1 \\\\ 2+2 = [output:B]', '\\ 2+2'],
    // no '=' on the line → whole segment before the placeholder
    ['2+2 [output:x]', '2+2'],
    // placeholder substitution: unknown/cycle → '0', non-finite → '(0)'
    ['[input:unknown] + [input:cyc] + [input:bad] = [output:r]', '0 + 0 + (0)'],
    // realistic aligned formula: '&' flattened, values substituted,
    // '\cdot' left for normaliseLatexForEvaluation
    [
      '\\begin{aligned}Gewinn &= [input:Umsatz] \\cdot [input:Marge] = [output:G]\\end{aligned}',
      '(1200) \\cdot (0.25)',
    ],
  ])('%j → %j', (rawLatex, expected) => {
    expect(extract(rawLatex)).toBe(expected)
  })

  it('returns "" for invalid placeholder offsets', () => {
    expect(getAutoExpressionFromLatexText('x = [output:x]', -1, resolve)).toBe('')
    expect(getAutoExpressionFromLatexText('x = [output:x]', NaN, resolve)).toBe('')
  })
})
