/**
 * LaTeX-to-expression normalisation for the LaTeX editor (PRD #28, slice 2 — #30).
 *
 * Faithful port of the standalone editor's FINAL patched behavior (reference
 * file latexEditor/latex_editor_FIXED_JSON_IMPORT_COMPLETE_OUTPUT_AS_INPUT_LATEX_FIX.htm.html,
 * "FINAL PATCH" layer):
 * - `normaliseLatexForEvaluation` ← lines 2242–2248 (with the balanced-brace
 *   helpers of lines 2238–2240), superseding the base script's non-nested
 *   regex version (lines 1569–1586).
 * - `getAutoExpressionFromLatexText` / `normaliseAutoExpressionText`
 *   ← lines 2257–2268, superseding the base script's match-based version
 *   (lines 931–953). Note: the final version has NO ":" boundary rule — that
 *   rule only exists in the DOM tokenized-line `getAutoExpression` for text
 *   lines, which is ported with the field-resolver in slice 5 (#33).
 *
 * The original resolved `[input:x]`/`[output:x]` placeholders through DOM
 * lookups (`getFieldByName`/`getFieldValue`) with a `visited` cycle set; this
 * pure module takes a {@link PlaceholderResolver} callback instead. Cycle
 * bookkeeping stays with the caller (field-resolver, slices 5/6), which
 * returns `null` for visited or unknown fields.
 *
 * Quirks preserved bug-for-bug (goldens generated by executing the original
 * in Node — these are the parity contract, agreed in #30 planning):
 * - Decimal-comma conversion is a single non-overlapping pass, so
 *   `1,2,3` → `1.2,3` (the second comma survives).
 * - After a `\\` line break, the detected line start points at the SECOND
 *   backslash, so the extracted segment keeps a stray `\` — which also flips
 *   the label heuristic (backslash counts as a "label" character).
 * - `\frac` with unbalanced braces keeps its token (`\frac{1}` → `\frac(1)`
 *   after brace conversion); `\sqrt` without a braced argument keeps its
 *   token and drops the following whitespace (`\sqrt 2` → `\sqrt2`).
 *
 * Pure and DOM-free — reusable by the future student-facing renderer.
 */

/**
 * Resolves a `[input:name]` / `[output:name]` placeholder to the field's
 * current value. Return `null` for unknown fields and for fields already in
 * the caller's visited set (cycles) — both become `'0'` in the expression,
 * while non-finite values become `'(0)'` and finite values `'(value)'`,
 * exactly as in the original.
 */
export type PlaceholderResolver = (kind: 'input' | 'output', name: string) => number | null

/** Reads a balanced `{...}` group starting at `offset`; port of `readBalanced` (L2238). */
function readBalancedBraces(s: string, offset: number): { content: string; end: number } | null {
  if (s[offset] !== '{') return null
  let depth = 0
  for (let i = offset; i < s.length; i++) {
    if (s[i] === '{') depth++
    if (s[i] === '}') depth--
    if (depth === 0) return { content: s.slice(offset + 1, i), end: i }
  }
  return null
}

/** Recursive balanced-brace `\frac{num}{den}` → `((num)/(den))`; port of `replFrac` (L2239). */
function replaceFrac(s: string): string {
  const token = '\\frac'
  let out = ''
  let i = 0
  while (i < s.length) {
    const pos = s.indexOf(token, i)
    if (pos === -1) {
      out += s.slice(i)
      break
    }
    out += s.slice(i, pos)
    let j = pos + token.length
    while (j < s.length && /\s/.test(s[j])) j++
    const num = readBalancedBraces(s, j)
    if (!num) {
      out += token
      i = j
      continue
    }
    j = num.end + 1
    while (j < s.length && /\s/.test(s[j])) j++
    const den = readBalancedBraces(s, j)
    if (!den) {
      out += token + '{' + num.content + '}'
      i = j
      continue
    }
    out += '((' + replaceFrac(num.content) + ')/(' + replaceFrac(den.content) + '))'
    i = den.end + 1
  }
  return out
}

/** Balanced-brace `\cmd{arg}` → `replacement(arg)` (non-recursive); port of `replOne` (L2240). */
function replaceCommand(s: string, cmd: string, replacement: string): string {
  const token = '\\' + cmd
  let out = ''
  let i = 0
  while (i < s.length) {
    const pos = s.indexOf(token, i)
    if (pos === -1) {
      out += s.slice(i)
      break
    }
    out += s.slice(i, pos)
    let j = pos + token.length
    while (j < s.length && /\s/.test(s[j])) j++
    const arg = readBalancedBraces(s, j)
    if (!arg) {
      out += token
      i = j
      continue
    }
    out += replacement + '(' + arg.content + ')'
    i = arg.end + 1
  }
  return out
}

/**
 * Translates a LaTeX expression into evaluator syntax. The replacement order
 * matches the original exactly (L2243–2247).
 */
export function normaliseLatexForEvaluation(expr: string): string {
  let p = expr || ''
  p = p.replace(/\\begin\{[^}]+\}|\\end\{[^}]+\}/g, ' ')
  p = p.replace(/\\\\(?:\s*\[[^\]]*\])?/g, ' ')
  p = p.replace(/&/g, ' ')
  p = p.replace(/\\,|\\;|\\:|\\!|\\quad|\\qquad|~/g, ' ')
  p = p.replace(/\\left|\\right/g, '')
  p = p.replace(/\\(?:mathrm|mathbf|mathit|text|operatorname)\s*\{([^{}]*)\}/g, '$1')
  p = replaceFrac(p)
  p = replaceCommand(p, 'sqrt', 'sqrt')
  p = p.replace(/\\pi\b/g, 'pi')
  p = p.replace(/\\cdot|\\times/g, '*')
  p = p.replace(/\\div/g, '/')
  p = p
    .replace(/\\sin\b/g, 'sin')
    .replace(/\\cos\b/g, 'cos')
    .replace(/\\tan\b/g, 'tan')
    .replace(/\\ln\b/g, 'ln')
    .replace(/\\log\b/g, 'log')
    .replace(/\\abs\b/g, 'abs')
  p = p.replace(/(\d),(\d)/g, '$1.$2')
  p = p.replace(/\{/g, '(').replace(/\}/g, ')')
  p = p.replace(/\^/g, '**')
  return p
}

/**
 * Strips alignment/environment noise from an auto-expression segment and
 * substitutes `[input:x]`/`[output:x]` placeholders via the resolver.
 * Port of `normaliseAutoExpressionText` (L2257–2261).
 */
export function normaliseAutoExpressionText(exprText: string, resolve: PlaceholderResolver): string {
  let e = (exprText || '').trim()
  e = e.replace(/&/g, ' ')
  e = e.replace(/\\begin\{[^}]+\}|\\end\{[^}]+\}/g, ' ')
  e = e.replace(/\\\\(?:\s*\[[^\]]*\])?/g, ' ')
  e = e.replace(/\[(input|output):([^\]]+)\]/g, (_match, kind: string, name: string) => {
    const v = resolve(kind as 'input' | 'output', name.trim())
    if (v === null) return '0'
    return Number.isFinite(v) ? '(' + v + ')' : '(0)'
  })
  return e.trim()
}

/**
 * Derives the expression for an `[output:x]` placeholder from its position in
 * the raw LaTeX source. Port of `getAutoExpressionFromLatexText` (L2263–2268):
 * - Line boundaries: the last `\n` or `\\` before the placeholder.
 * - No `=` on the line → the whole segment before the placeholder.
 * - Two or more `=` → the text between the last two `=`.
 * - Exactly one `=` → label detection decides between the text before the
 *   `=` and the text between `=` and the placeholder: the before-part is a
 *   label when it contains letters/backslashes/`&` but no operators, `\frac`,
 *   `\sqrt`, `\cdot`, `\times` or digits.
 */
export function getAutoExpressionFromLatexText(
  rawLatex: string,
  placeholderStart: number,
  resolve: PlaceholderResolver,
): string {
  const idx = Number(placeholderStart)
  if (!Number.isFinite(idx) || idx < 0) return ''
  const lastNewline = rawLatex.lastIndexOf('\n', idx - 1)
  const lastBreak = rawLatex.lastIndexOf('\\\\', idx - 1)
  const lineStart = Math.max(lastNewline, lastBreak) + 1
  const before = rawLatex.substring(lineStart, idx)
  const eq: number[] = []
  for (let i = 0; i < before.length; i++) {
    if (before[i] === '=') eq.push(lineStart + i)
  }
  if (!eq.length) return normaliseAutoExpressionText(before, resolve)
  let expr = ''
  if (eq.length >= 2) {
    expr = rawLatex.substring(eq[eq.length - 2] + 1, eq[eq.length - 1])
  } else {
    const only = eq[0]
    const b = rawLatex.substring(lineStart, only)
    const a = rawLatex.substring(only + 1, idx)
    const after = normaliseAutoExpressionText(a, resolve)
    const label =
      /[A-Za-z\\]|&/.test(b) && !/[+\-*/^]|\\frac|\\sqrt|\\cdot|\\times|\d/.test(b.replace(/&/g, ''))
    expr = after && label ? a : b
  }
  return normaliseAutoExpressionText(expr, resolve)
}
