/**
 * Golden parity tests for the display-direction LaTeX helpers (#31).
 *
 * Every expected value was generated by executing the standalone editor in a
 * browser: `cleanupLatex` (base script L751) directly, and
 * `prettifyMultiplicationStars` through the final patch layer's
 * `resolveFieldPlaceholders` with zero fields on the page (placeholders pass
 * through verbatim there, so only the star prettification applies) — these
 * tests are the port's parity contract.
 */
import { describe, expect, it } from 'vitest'
import { cleanupLatex, prettifyMultiplicationStars } from './latex-display'

describe('cleanupLatex', () => {
  it.each<[string, string]>([
    // $$…$$ delimiters stripped, content trimmed
    ['$$ a^2+b^2=c^2 $$', 'a^2+b^2=c^2'],
    // \[…\] delimiters stripped
    ['\\[ x \\]', 'x'],
    // multiple backslashes before the bracket are tolerated (\\+ in the regex)
    ['\\\\[ x \\\\]', 'x'],
    // one-sided delimiters are stripped too
    ['$$x', 'x'],
    ['x$$', 'x'],
    ['$$', ''],
    // plain trimming
    ['  a+b  ', 'a+b'],
    // INNER delimiters are not touched — only leading/trailing ones
    ['a $$ b', 'a $$ b'],
    // no delimiters: unchanged
    ['\\frac{1}{2}', '\\frac{1}{2}'],
    ['', ''],
  ])('%j → %j', (input, expected) => {
    expect(cleanupLatex(input)).toBe(expected)
  })
})

describe('prettifyMultiplicationStars', () => {
  it.each<[string, string]>([
    // single stars become spaced \cdot
    ['a*b', 'a\\,\\cdot\\,b'],
    ['2*3*4', '2\\,\\cdot\\,3\\,\\cdot\\,4'],
    // string-edge stars convert too (prev/next are '')
    ['*a', '\\,\\cdot\\,a'],
    ['a*', 'a\\,\\cdot\\,'],
    // doubled stars (exponent-style) survive untouched — every star in a
    // run has a star neighbour
    ['2**3', '2**3'],
    ['***', '***'],
    // escaped star survives
    ['a\\*b', 'a\\*b'],
    // stars inside \begin{…}/\end{…} tokens are protected by the sentinel
    // round-trip; stars between them still convert
    ['\\begin{a*b}x*y\\end{a*b}', '\\begin{a*b}x\\,\\cdot\\,y\\end{a*b}'],
    [
      '\\begin{aligned}a &= b*c \\\\ d &= e\\end{aligned}',
      '\\begin{aligned}a &= b\\,\\cdot\\,c \\\\ d &= e\\end{aligned}',
    ],
    // field placeholders are none of this function's business
    ['[input:Umsatz]*[input:Marge]', '[input:Umsatz]\\,\\cdot\\,[input:Marge]'],
    // no stars / empty: unchanged
    ['x + y', 'x + y'],
    ['', ''],
  ])('%j → %j', (input, expected) => {
    expect(prettifyMultiplicationStars(input)).toBe(expected)
  })
})
