/**
 * Display-direction LaTeX helpers for the LaTeX editor (PRD #28, slice 3 — #31).
 *
 * Counterpart to latex-normalise.ts (which translates LaTeX *into*
 * evaluatable expressions); these two functions shape LaTeX *for rendering*.
 * Faithful port of the standalone reference file
 * latexEditor/latex_editor_FIXED_JSON_IMPORT_COMPLETE_OUTPUT_AS_INPUT_LATEX_FIX.htm.html:
 *
 * - `cleanupLatex` ← base script L751–756 (never patched).
 * - `prettifyMultiplicationStars` ← `prettifyMultiplicationStarsForDisplay`
 *   of the FINAL patch layer (`patch-output-as-input-latex-fix-v1`,
 *   L2665–2682), which subsumed the earlier standalone `\cdot` patch (L2641).
 *
 * Goldens in latex-display.test.ts were generated by executing the original
 * file in a browser — they are the parity contract.
 *
 * Pure and DOM-free — reusable by the future student-facing renderer.
 */

/**
 * Strips surrounding display-math delimiters (`$$…$$`, `\[…\]`, tolerating
 * multiple backslashes) and trims. Inner delimiters are left untouched.
 */
export function cleanupLatex(s: string): string {
  let x = (s || '').trim()
  x = x.replace(/^\s*\$\$\s*/, '').replace(/\s*\$\$\s*$/, '')
  x = x.replace(/^\s*\\+\[\s*/, '').replace(/\s*\\+\]\s*$/, '')
  return x.trim()
}

/**
 * Displays `*` as `\,\cdot\,` in rendered LaTeX. Stars that are escaped
 * (`\*`), doubled (`**`, exponent-style), or inside `\begin{…}`/`\end{…}`
 * tokens (protected via U+E000 sentinels) are left untouched.
 */
export function prettifyMultiplicationStars(latex: string): string {
  if (!latex) return latex
  const protectedParts: string[] = []
  const protectedLatex = latex.replace(/\\(?:begin|end)\{[^}]*\}/g, (m) => {
    const key = '\uE000' + protectedParts.length + '\uE000'
    protectedParts.push(m)
    return key
  })
  let out = ''
  for (let i = 0; i < protectedLatex.length; i++) {
    const ch = protectedLatex[i]
    const prev = i > 0 ? protectedLatex[i - 1] : ''
    const next = i + 1 < protectedLatex.length ? protectedLatex[i + 1] : ''
    out += ch === '*' && prev !== '\\' && prev !== '*' && next !== '*' ? '\\,\\cdot\\,' : ch
  }
  return out.replace(/\uE000(\d+)\uE000/g, (_, idx: string) => protectedParts[Number(idx)] || '')
}
