/**
 * Golden parity tests for the German number formatting (#30).
 *
 * Every expected value was generated by executing the standalone editor's
 * final `formatValue` (reference file line 2629, the "simple display
 * formatting" patch) in Node — these tests are the port's parity contract.
 */
import { describe, expect, it } from 'vitest'
import { formatValue } from './number-format'

describe('formatValue', () => {
  it.each<[number, string]>([
    [NaN, '—'],
    [Infinity, '—'],
    [-Infinity, '—'],
  ])('non-finite %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })

  it.each<[number, string]>([
    [-0, '0'],
    // rounding collapses to zero: no '-0' may survive
    [-0.00001, '0'],
  ])('negative zero %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })

  describe('magnitude tiers', () => {
    it.each<[number, string]>([
      // |v| > 1000 → 0 decimals
      [1234567.891, '1 234 568'],
      [1000.4, '1 000'],
      [-56789, '-56 789'],
      [12345678, '12 345 678'],
      // 10 ≤ |v| ≤ 1000 → 2 decimals
      [1000, '1 000'],
      [999.999, '1 000'], // rounding crosses the grouping boundary
      [42.126, '42,13'],
      [10, '10'],
      [100.1, '100,1'],
      [-1234.5678, '-1 235'],
      // 1 ≤ |v| < 10 → 3 decimals
      [3.14159, '3,142'],
      [9.9999, '10'],
      [2.5, '2,5'],
      // |v| < 1 → 4 decimals (tier chosen from the ORIGINAL value)
      [0.5, '0,5'],
      [-0.5, '-0,5'],
      [0.1234, '0,1234'],
      [0.123456, '0,1235'],
      [0.9999999, '1'],
    ])('%d → %j', (input, expected) => {
      expect(formatValue(input)).toBe(expected)
    })
  })

  it.each<[number, string]>([
    [0, '0'],
    [7, '7'],
  ])('integer %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })
})
